builder.config.json
src/components/interaction-designer/block-types/MobilePrimitives_SelectManyResponseBlock.vue
src/components/interaction-designer/flow-editors/FirstBlockEditorButton.vue
src/store/builder/2019-10-10-shortcut-flow.json
src/store/flow/block-types/MobilePrimitives_NumericResponseBlockStore.ts
src/store/flow/flow.ts
src/views/InteractionDesigner.vue

There are few issues which were a bit complicated to me, I'd like to ask you @jacob-viamo to look at them and try to find a solution if possible:
1- Cannot add select many: when adding SelectMany block from menu, SelectOne is added instead
2- Resource Editor not working for new added block
3- When adding CaseBlock, we have no label on exits

VMO-2224 fixes after resolving conflicts from Brett's styling

---

builder.config.json
src/components/interaction-designer/Block.vue
src/components/interaction-designer/block-types/Core_LogBlock.vue
src/components/interaction-designer/block-types/MobilePrimitives_SelectManyResponseBlock.vue
src/components/interaction-designer/block-types/MobilePrimitives_SelectOneResponseBlock.vue
src/components/interaction-designer/resource-editors/ResourceEditor.vue
src/store/builder/blank-flow.json
src/store/builder/index.ts
src/store/flow/block-types/Core_CaseBlockStore.ts
src/store/flow/block-types/Core_LogBlockStore.ts
src/store/flow/block-types/MobilePrimitives_SelectManyResponseBlockStore.ts
src/store/flow/block-types/MobilePrimitives_SelectOneResponseBlockStore.ts
src/store/flow/block.ts
src/store/flow/flow.ts
src/store/flow/resource.ts

Hi @jcbashdown I shared that I'd have this out, but there are two fixes remaining as you review.
---
---

Vmo 2671 fix misc bugs before qa

---

src/components/common/NumericEditor.vue
src/components/interaction-designer/block-editors/MaxDigitEditor.vue
src/components/interaction-designer/block-editors/MaxDurationSecondsEditor.vue
src/components/interaction-designer/block-editors/MaxResponseCharactersEditor.vue
src/components/interaction-designer/block-editors/MaximumNumericEditor.vue
src/components/interaction-designer/block-editors/MinimumNumericEditor.vue
src/components/interaction-designer/block-editors/TimeoutEditor.vue
src/components/interaction-designer/block-types/MobilePrimitives_NumericResponseBlock.vue
src/components/interaction-designer/flow-editors/InteractionTimeoutEditor.vue

a very quick fix:
- fix event on max-digit-editor
- fix some positive number filtering

VMO-2870 fix block-max-digit-editor

---

src/components/common/FloatEditor.vue
src/components/interaction-designer/block-editors/ThresholdEditor.vue
src/components/interaction-designer/flow-editors/FirstBlockEditorButton.vue
src/store/builder/blank-flow.json
src/store/flow/block.ts
src/store/flow/flow.ts

Will merge to master once approved

Vmo 3090 fix bugs found during qa round 1

---

src/components/interaction-designer/toolbar/TreeBuilderToolbar.vue

This is a test to let us know if merged PR will be deployed on gh-pages automatically

VMO-3601 test minor UI change

---

.travis.yml

An attempt to allow conditional builds

VMO-3601 add conditional builds

---

.travis.yml
src/components/interaction-designer/toolbar/TreeBuilderToolbar.vue

Vmo 3601 GitHub pages auto rebuild

---

.travis.yml
src/components/interaction-designer/toolbar/TreeBuilderToolbar.vue

Vmo 3601 test auto deploy on gh pages

---

src/store/flow/block-types/Core_CaseBlockStore.ts
src/store/flow/block-types/MobilePrimitives_NumericResponseBlockStore.ts
src/store/flow/block-types/MobilePrimitives_OpenResponseBlockStore.ts
src/store/flow/block-types/MobilePrimitives_SelectManyResponseBlockStore.ts
src/store/flow/block-types/MobilePrimitives_SelectOneResponseBlockStore.ts

I fixed most the schema issue.
But the selectMany still has issues, I don't know why ? 
I created this ticket to handle the fix: https://viamoinc.atlassian.net/browse/VMO-4048

Vmo 3616 correct missed schema

---

package.json
src/components/interaction-designer/block-types/Core_SetGroupMembershipBlock.vue
src/store/flow/block-types/Core_SetGroupMembershipStore.ts
src/store/flow/block-types/MobilePrimitives_NumericResponseBlockStore.ts
src/store/flow/block-types/MobilePrimitives_OpenResponseBlockStore.ts
src/store/flow/block-types/MobilePrimitives_SelectManyResponseBlockStore.ts
src/store/flow/block-types/MobilePrimitives_SelectOneResponseBlockStore.ts
yarn.lock

For now, I considered Android chapter's change on `ISetGroupMembershipBlockConfig.ts::is_member` to be a boolean. In case we will change it in the future, we will re-update flow-builder.
Mode details, check this slack thread: https://votomobile.slack.com/archives/C2CEV043B/p1620741416125400

Vmo 4048 fix some validation schemas

---

src/components/interaction-designer/Block.vue

VMO-3681 Block label icons - Starting block

---

src/components/interaction-designer/clipboard/ClipboardRoot.vue
src/components/interaction-designer/clipboard/prompt-kinds/Message.vue
src/components/interaction-designer/clipboard/prompt-kinds/Numeric.vue
src/components/interaction-designer/clipboard/prompt-kinds/Open.vue
src/components/interaction-designer/clipboard/prompt-kinds/SelectMany.vue
src/components/interaction-designer/clipboard/prompt-kinds/SelectOne.vue
src/components/interaction-designer/clipboard/shared/PromptKindMixin.ts
src/components/interaction-designer/toolbar/TreeBuilderToolbar.vue
src/store/clipboard/index.ts
src/store/flow/block-types/MobilePrimitives_NumericResponseBlockStore.ts
tests/unit/__snapshots__/storybook.spec.ts.snap

Note: 
Marked it as Work in Progress (WIP) as there are a few console errors that I need to take care
This ticket might need further refactoring.
Update: 
Tried refactoring common code between the prompt kinds using mixins. Please take a look and suggest if there are better ways to achieve a refactor.

VMO-3705 Port simulator to typescript vue

---

package.json
yarn.lock

I adapted what we already have in flow-runner

VMO-3119 add new yarn commands for build & tagging

---

src/components/interaction-designer/block-types/MobilePrimitives_SelectOneResponseBlock.vue
src/components/interaction-designer/resource-editors/ResourceVariantTextEditor.vue

Hi @poojahpatil90, I've merged the simplified choices but wanted to get this fix in there as well which allows us to provide # of rows to the resource variant textarea.

VMO-4140 Add prop for textarea # of rows on resource-variant-text-editor

---

src/components/interaction-designer/block-types/MobilePrimitives_SelectOneResponseBlock.vue

Swap positions of choices and prompt.

VMO-4140 Swap choices + prompt positions.

---

src/components/interaction-designer/Block.vue
src/components/interaction-designer/toolbar/TreeBuilderToolbar.vue

VMO-4315 hide selection banner on view mode

---

src/components/interaction-designer/Block.vue
src/components/interaction-designer/Connection.vue
src/components/interaction-designer/block-editors/MaxDigitEditor.vue
src/views/InteractionDesigner.vue

VMO-4307 + VMO-4308 + VMO-4309  Fixes for these tickets

---

src/store/flow/flow.ts
tests/unit/__snapshots__/storybook.spec.ts.snap

Duplicated block has now a cloned resource from the originating block:

Vmo 4317 fix resource config for duplicated block

---

tests/unit/__snapshots__/storybook.spec.ts.snap

Inspected in builder and storybook and can't see a problem
Fixing now to reduce noise

VMO-4246 - fix storyshots - some better some worse

---

src/components/interaction-designer/block-types/Core_OutputBlock.vue

Note:
- setting exit.value when having Single exit mode will be done in vmo-4322
- in master, we already have setContactProp & Categorization
Screenshot

VMO-4162 add BlockOutputBranchingConfig

---

src/components/common/ExpressionInput.vue
src/components/interaction-designer/block-editors/GenericContactPropertyEditor.vue
tests/unit/__snapshots__/storybook.spec.ts.snap

VMO-4348 fix UI & default radio button

---

src/components/interaction-designer/block-editors/AdvancedExitEditor.vue
src/components/interaction-designer/block-editors/AdvancedExitsBuilder.vue
src/components/interaction-designer/block-editors/ChoicesBuilder.vue
src/components/interaction-designer/block-types/MobilePrimitives_SelectOneResponseBlock.vue
src/store/flow/block.ts
src/store/validation/index.ts

Hi @safydy @poojahpatil90 , this resolves the funky blurring and reordering of choices and exits in SelectOne popout.

Vmo 4208 exit config

---

src/components/interaction-designer/block-types/Core_SetContactPropertyBlock.vue

VMO-4142 add exit branching

---

src/components/common/ExpressionInput.vue
src/components/interaction-designer/block-types/ConsoleIO_PrintBlock.vue
src/components/interaction-designer/block-types/ConsoleIO_ReadBlock.vue
src/components/interaction-designer/block-types/Core_CaseBlock.vue
src/components/interaction-designer/block-types/Core_LogBlock.vue
src/components/interaction-designer/block-types/Core_OutputBlock.vue
src/components/interaction-designer/block-types/Core_RunFlowBlock.vue
src/components/interaction-designer/block-types/Core_SetContactPropertyBlock.vue
src/components/interaction-designer/block-types/Core_SetGroupMembershipBlock.vue
src/components/interaction-designer/block-types/MobilePrimitives_MessageBlock.vue
src/components/interaction-designer/block-types/MobilePrimitives_NumericResponseBlock.vue
src/components/interaction-designer/block-types/MobilePrimitives_OpenResponseBlock.vue
src/components/interaction-designer/block-types/MobilePrimitives_SelectManyResponseBlock.vue
src/components/interaction-designer/block-types/SmartDevices_LocationResponseBlock.vue
src/components/interaction-designer/block-types/SmartDevices_PhotoResponseBlock.vue
src/store/flow/block-types/Core_OutputBlockStore.ts
tests/unit/__snapshots__/storybook.spec.ts.snap

I took the opportunity to allow us having null value on ExpressionInput, so we can see validation if we provide `null` value for example.

Vmo 4383 update block config title

---

src/components/interaction-designer/block-editors/BlockOutputBranchingConfig.vue
src/components/interaction-designer/block-types/Core_CaseBlock.vue
src/components/interaction-designer/resource-editors/ResourceEditor.vue
src/store/flow/block-types/Core_CaseBlockStore.ts
tests/unit/__snapshots__/storybook.spec.ts.snap

Includes a fix for a CSS compilation warning

Vmo 4161 unified case block

---

src/store/flow/block-types/ConsoleIO_PrintBlockStore.ts
src/store/flow/block-types/ConsoleIO_ReadBlockStore.ts
src/store/flow/block-types/Core_CaseBlockStore.ts
src/store/flow/block-types/Core_LogBlockStore.ts
src/store/flow/block-types/Core_OutputBlockStore.ts
src/store/flow/block-types/Core_RunFlowBlockStore.ts
src/store/flow/block-types/Core_SetContactPropertyStore.ts
src/store/flow/block-types/Core_SetGroupMembershipStore.ts
src/store/flow/block-types/MobilePrimitives_MessageBlockStore.ts
src/store/flow/block-types/MobilePrimitives_NumericResponseBlockStore.ts
src/store/flow/block-types/MobilePrimitives_OpenResponseBlockStore.ts
src/store/flow/block-types/MobilePrimitives_SelectManyResponseBlockStore.ts
src/store/flow/block-types/MobilePrimitives_SelectOneResponseBlockStore.ts
src/store/flow/block-types/SmartDevices_LocationResponseBlockStore.ts
src/store/flow/block-types/SmartDevices_PhotoResponseBlockStore.ts
src/store/validation/index.ts
src/store/validation/validationHelpers.ts

@safydy-r  I took the opportunity with this task to move some of the helper functions in validation store to `validationHelper.ts` file. Please go through it and let me know your thoughts.

VMO-4136 Validation should delegate to individual block stores to each validate themselves Part 1

---

src/components/common/ValidationMessage.vue
src/components/interaction-designer/toolbar/ErrorNotifications.vue
src/store/validation/index.ts
tests/unit/__snapshots__/storybook.spec.ts.snap

VMO-4312 Show error on click of Fix Issue in notification bar or when an input field is touched

---

.eslintrc.js
config/eslint/index.js
config/eslint/lib/helpers.js
config/eslint/lib/rules/vue-root-class-name.js
package.json
yarn.lock

A proposal on enforcing code convention with ESLint.

VMO-5604 Validate class names with a custom ESLint rule

---

src/components/common/AudioLibrarySelection.vue
src/components/common/AudioLibrarySelector.vue
src/components/interaction-designer/resource-editors/ResourceEditor.vue
src/store/trees/audio.js

This will allow us to:
- display audio description in UI
- but sending audio URI as resource value

VMO-4326 display audio description in the UI

---

src/store/flow/flow.ts

https://user-images.githubusercontent.com/3971957/168307964-346aa139-a426-4203-b404-a6c2cac7dfc6.mov

VMO-5825 Validation error for adding a block still shows even when there are existing blocks in the flow

---

src/components/interaction-designer/blocks/BlockToolbar.vue

VMO-6347 Display Show/Hide Editor button in View mode

---

package.json
src/components/interaction-designer/toolbar/TreeBuilderToolbar.vue
src/store/builder/index.ts
src/store/flow/block-types/BaseBlock.ts
src/store/flow/block-types/Core_CaseBlockStore.ts
src/store/flow/flow.ts

Note:
- inspired from @object-required 's PR https://github.com/FLOIP/flow-builder/pull/279
- by trying to set default props at the block creation as possible

Feature/vmo 6481/fix case block validation  with more refactoring

---

src/store/flow/block.ts
src/store/flow/block/set-contact-property.ts

Fix issues that I had in voto5:
- turn `block_getContactPropertyOnIndex` and `block_getContactPropertyValueByKey` into getters which are synchronous. (They were actions and were returning promises. We couldn't await there)
- use double arrow function because we need to provide params (with regular getters we don't use params). This is called [method-style access](https://vuex.vuejs.org/guide/getters.html#method-style-access)

Feature/vmo 6309/fix get property action

---

builder.config.json
package.json
src/components/interaction-designer/block-editors/BlockOutputBranchingConfig.vue
src/components/interaction-designer/block-editors/ChoicesBuilder.vue
src/components/interaction-designer/block-types/MobilePrimitives_SelectOneResponseBlock.vue
src/components/interaction-designer/toolbar/BlockErrorsExpandable.vue
src/store/flow/block-types/MobilePrimitives_SelectManyResponseBlockStore.ts
src/store/flow/block-types/MobilePrimitives_SelectOneResponseBlockStore.ts
src/store/flow/block.ts
src/store/flow/resource.ts
yarn.lock

Feature/vmo 6181/mcq single exit and advanced exits

---

src/assets/messages.json
src/components/interaction-designer/block-editors/choices/ChoiceMappingModal.vue
src/lib.ts
src/lib/validations/ExtendedValidatorBase.ts
src/lib/validations/MobilePrimitives_SelectOneResponseBlockValidator.ts
src/lib/validations/index.ts
src/store/builder/index.ts
src/store/flow/block-types/MobilePrimitives_SelectOneResponseBlockStore.ts
src/store/validation/index.ts

Feature/vmo 5463/vmo 6647/mcq validation duplicates ivr test expression

---

package.json
src/assets/messages.json
src/components/interaction-designer/block-editors/choices/ChoiceMappingModal.vue
src/components/interaction-designer/block-editors/choices/ChoicesBuilder.vue
src/lib/validations/MobilePrimitives_SelectOneResponseBlockValidator.ts
yarn.lock

Feature/vmo 5463/vmo 6702/do not allow empty choices mcq

---

src/store/flow/block/choice.ts

https://user-images.githubusercontent.com/3971957/183838836-6c77f245-528e-465e-842f-0973b40c7405.mp4

VMO-6651 Update 1st synonyms

---

builder.config.json
src/components/interaction-designer/flow-editors/import/TechErrorNotifications.vue
src/store/flow/flow.ts
src/store/flow/views/import.ts
src/store/validation/index.ts
src/views/ImportFlow.vue
vue.config.js

Note for devs:
- using the `vue.config` to mock a new endpoint
- then re-use validation approach used in vmo-6755 to display it
[overview in case of an error]

Feature/vmo 3952/vmo 6756/display backend validation for import flow

---

package.json
yarn.lock

VMO-6585 Consume the changes from flow-runner

---

src/components/interaction-designer/Block.vue

VMO-6575 Adjust button spacing

---

src/components/interaction-designer/Block.vue

VMO-6572 Adjust editor position

---

src/components/interaction-designer/resource-editors/PerLanguageResourceEditorRow.vue
src/components/interaction-designer/resource-editors/PerModeResourceEditor.vue
src/font-awesome-icon.ts

Feature/vmo 6851/vmo 7101/update icons for show hide action

---

src/store/validation/index.ts

Solution:
- clean backend validation in store before we validate again
For demo, see voto5 PR instead

Hotfix/vmo 7145/vmo 7179/fix validations after save

---

dist/types/components/interaction-designer/block-editors/choices/expressionTransformers.d.ts
dist/types/store/flow/block/choice.d.ts
src/components/interaction-designer/block-editors/choices/TextSynonymsEditor.vue
src/components/interaction-designer/block-editors/choices/expressionTransformers.ts
src/store/flow/block-types/MobilePrimitives_SelectOneResponseBlockStore.ts
src/store/flow/block.ts
src/store/flow/block/choice.ts
vue.config.js

------ Fix 1 ------
------ Fix 2 ------

Feature/vmo 7069/escape choice tests and exits

---

dist/types/components/interaction-designer/ResourceViewer.vue.d.ts
dist/types/components/interaction-designer/flow-editors/FlowEditor.vue.d.ts
dist/types/components/interaction-designer/toolbar/TreeBuilderToolbar.vue.d.ts
dist/types/views/InteractionDesigner.vue.d.ts
src/components/interaction-designer/flow-editors/FlowEditor.vue
src/store/flow/flow.ts

The flow persistence is cleaning the resource, see: https://github.com/FLOIP/flow-builder/blob/master/src/store/flow/flow.ts#L210
but for some release we don't have this `flow_addMissingResourceValues` from @object-required anymore, very strange.
The solution:
- put flow_addMissingResourceValues back
-  and call it when we edit the flow languages/modes
TODO after merge

Feature/vmo 6851/vmo 7195/fix missing resource variant

---

dist/types/components/interaction-designer/block-editors/choices/ChoicesBuilder.vue.d.ts
src/components/interaction-designer/block-editors/choices/ChoicesBuilder.vue
src/store/flow/flow.ts
src/store/flow/resource.ts

[overview]
This json provides us an eg. of a flow having orphan resource  [flow with orphan choice resource.txt](https://github.com/FLOIP/flow-builder/files/9933817/flow.with.orphan.choice.resource.txt)

Hotfix/vmo 6643/safely clean delete choices

---

src/components/interaction-designer/toolbar/TreeBuilderToolbar.vue

voto5 PR: https://bitbucket.org/voto/voto5/pull-requests/2870/feature-vmo-6880-vmo-7350-search-input-ui

Feature/vmo 6880/vmo 7350/search input UI

---

package.json

In voto5:
- before (without `types`)
- after (with `types`)

Feature/vmo 7383/include types when installed as dep

---

dist/types/components/interaction-designer/block-editors/AdvancedExitsBuilder.vue.d.ts
src/components/interaction-designer/block-editors/AdvancedExitEditor.vue
src/components/interaction-designer/block-editors/AdvancedExitsBuilder.vue

CORE-19 Advanced menu UI configuration

---

package.json
src/store/flow/block.ts
src/utils/string-utils.ts

Basically we just replace spaces with underscore and make the string to lower case.
update overview

Feature/core 48/customize snake case method for label generation

---

package.json
src/assets/messages.json
yarn.lock

[Changes]
This is just to consume changes from flow-blocker-runner

CORE-84 consume 1st PR from fbr

---

dist/types/lib.d.ts
package.json

Context: 
- when I try to consume this, the associated flow-runner is not updated
- I'm trying to update the subversion, to check if I get this one right

CORE-84 just re-build it to try fixing some version error

---

src/components/common/PlainDraggable.vue
src/components/interaction-designer/block/Block.vue
src/store/builder/index.ts
src/store/flow/flow.ts

[Screencast from 2023-05-29 04:24:40 PM.webm](https://github.com/FLOIP/flow-builder/assets/3971957/0123ea66-3d7d-4874-89d8-ab88c0b71486)

CORE-538, CORE-544 Handle move block action

---

cspell.json
src/store/undoRedo/getChangedKeys.ts
src/store/undoRedo/index.ts
src/utils/type-utils.ts

[Screencast from 2023-06-06 03:34:42 PM.webm](https://github.com/FLOIP/flow-builder/assets/3971957/0a8e9e59-fc6c-44b6-9399-02b9ca8bda11)

CORE-538, CORE-578 Fix getChangedKeys
