- package.json
- src/components/interaction-designer/toolbar/TreeBuilderToolbar.vue
- src/router/index.ts
- src/store/trees/trees.js
- src/stories/Toolbar.stories.ts
- src/stories/story-utils/FlowBuilderContainer.vue
- src/stories/story-utils/FlowBuilderSidebarEditorContainer.vue
- yarn.lock
This PR is about to "extend the toolbar component"
I took the opportunity to add toolbar stories, meaning this was branched out of [VMO-2642-move-storybook-stories-from-voto5](https://github.com/FLOIP/flow-builder/tree/VMO-2642-move-storybook-stories-from-voto5)
Therefore, the merge plan is:
- merge vmo-2642 to master
- change the destination of this PR to master, merge it
Story sample
> Vmo 2926 match flow builder toolbar actions with voto5 -- extend toolbar

- tsconfig.json
It was a ts issue on storybook. I'm wondering why we didn't have it before?
My proposal is just to exclude storybook from `tsconfig.json`
> VMO-3432 fix-type-c-does-not-satisfy-the-constraint

- package.json
- src/components/interaction-designer/block-types/ConsoleIO_PrintBlock.vue
- src/components/interaction-designer/block-types/ConsoleIO_ReadBlock.vue
- src/components/interaction-designer/block-types/Core_CaseBlock.vue
- src/components/interaction-designer/block-types/Core_LogBlock.vue
- src/components/interaction-designer/block-types/Core_OutputBlock.vue
- src/components/interaction-designer/block-types/Core_RunFlowBlock.vue
- src/components/interaction-designer/block-types/MobilePrimitives_MessageBlock.vue
- src/components/interaction-designer/block-types/MobilePrimitives_NumericResponseBlock.vue
- src/components/interaction-designer/block-types/MobilePrimitives_OpenResponseBlock.vue
- src/components/interaction-designer/block-types/MobilePrimitives_SelectOneResponseBlock.vue
- src/components/interaction-designer/flow-editors/LanguagesEditor.vue
- src/components/interaction-designer/resource-editors/ResourceEditor.vue
- src/store/builder/index.ts
- src/store/flow/block-types/ConsoleIO_PrintBlockStore.ts
- src/store/flow/block-types/ConsoleIO_ReadBlockStore.ts
- src/store/flow/block-types/Core_CaseBlockStore.ts
- src/store/flow/block-types/Core_LogBlockStore.ts
- src/store/flow/block-types/Core_OutputBlockStore.ts
- src/store/flow/block-types/Core_RunFlowBlockStore.ts
- src/store/flow/block-types/MobilePrimitives_MessageBlockStore.ts
- src/store/flow/block-types/MobilePrimitives_NumericResponseBlockStore.ts
- src/store/flow/block-types/MobilePrimitives_OpenResponseBlockStore.ts
- src/store/flow/block-types/MobilePrimitives_SelectManyResponseBlockStore.ts
- src/store/flow/block-types/MobilePrimitives_SelectOneResponseBlockStore.ts
- src/store/flow/block-types/SmartDevices_LocationResponseBlockStore.ts
- src/store/flow/block-types/SmartDevices_PhotoResponseBlockStore.ts
- src/store/flow/block.ts
- src/store/flow/resource.ts
- yarn.lock
I updated the usage of flow-runner because I need to have access to `@floip/flow-runner/src/model/block/IBlockConfig.ts`.
After the update, there were some import fixes we had to change.
I decided to separate the PR from upcoming implementation to have cleaner diffs.
[Merge plan]
Waiting for the whole vmo-2296 review
> VMO-2296 use flow-runner v0.0.95

- src/components/interaction-designer/block-types/ConsoleIO_PrintBlock.vue
- src/components/interaction-designer/block-types/ConsoleIO_ReadBlock.vue
- src/components/interaction-designer/block-types/Core_CaseBlock.vue
- src/components/interaction-designer/block-types/Core_LogBlock.vue
- src/components/interaction-designer/block-types/Core_OutputBlock.vue
- src/components/interaction-designer/block-types/Core_RunFlowBlock.vue
- src/components/interaction-designer/block-types/Core_SetContactPropertyBlock.vue
- src/components/interaction-designer/block-types/Core_SetGroupMembershipBlock.vue
- src/components/interaction-designer/block-types/MobilePrimitives_MessageBlock.vue
- src/components/interaction-designer/block-types/MobilePrimitives_NumericResponseBlock.vue
- src/components/interaction-designer/block-types/MobilePrimitives_OpenResponseBlock.vue
- src/components/interaction-designer/block-types/MobilePrimitives_SelectManyResponseBlock.vue
- src/components/interaction-designer/block-types/MobilePrimitives_SelectOneResponseBlock.vue
- src/components/interaction-designer/block-types/SmartDevices_LocationResponseBlock.vue
- src/components/interaction-designer/block-types/SmartDevices_PhotoResponseBlock.vue
- src/views/InteractionDesigner.vue
Added extras slot above the options section which shows the set first block button. The screenshot shows some test label and input field that I added(but removed in this PR).
> VMO-3746 [Viamo Blocks] Add #extends slot to Community Flow Builder blocks

- src/views/InteractionDesigner.vue
The second argument for router.replace is onload. To use a query param it should be done like this. I'm 100% I tested this multiple times during the flow lifecycle work so I don't really understand how this became broken but this fixes it!
> VMO-3120 - fix flow lifecycle

- src/components/interaction-designer/Block.vue
@poojahpatil90 @safydy Do you think this is a fair solution? I simply background:white + fade-in toolbar right over top of the block. I've inherited borders to make it easier to match up if we adjust styling in the future.
> Vmo 4212 block toolbar on hover

- src/components/interaction-designer/BuilderCanvas.vue
- src/components/interaction-designer/Connection.vue
- src/store/builder/index.ts
The pbm was we put `block.ui_metadata...` rather than `ui_metadata...` in `lodash.get` path. I took the opportunity to remove the usage of `get()` in some part of the code.
Screenshots
> Vmo 4323 fix overlapping blocks

- src/assets/messages.json
- src/components/interaction-designer/block-editors/PhotoPromptEditor.vue
- src/components/interaction-designer/block-types/SmartDevices_PhotoResponseBlock.vue
- src/store/flow/block-types/SmartDevices_PhotoResponseBlockStore.ts
- tests/unit/__snapshots__/storybook.spec.ts.snap
**Note**:
- setting exit.value when having Single exit mode will be done in vmo-4322
- in master, we already have setContactProp & Categorization
About `prompt` implementation, I had this [thread](https://votomobile.slack.com/archives/CGGFKUP4Y/p1627083068197500) on squad2 channel to confirm it should be localized
Screenshots
> Vmo 4149 unified block photo response

- src/store/builder/5b8c87d6-de90-4bc4-8668-4f040000006e-valid-flow.json
- src/store/builder/f0492216-65f3-4dc7-a1d8-8f79d1d30c11-flow.json
- src/store/flow/block.ts
Setting to null when you don't finish connecting a block is invalid - unset completely.
Update some example flows as currently the config for these test flows is missing some important exit defaults we have added recently. Without these if you play with exits without viewing the block sidebar first then things can behave strangely.
I wasn't able to reproduce the first problem with this ticket. I've asked Jon for further instructions. Let's try and get this one in and I'll do that in a separate PR.
> VMO-4346 - fix exit becoming invalid value on create without target

- src/components/interaction-designer/Block.vue
Solution: We should not hide exit draggables on view mode, because connections are bound with them.
[After fix]
> VMO-4328 do not remove exits draggable for view mode

- src/components/interaction-designer/BuilderCanvas.vue
This is a temporary solution, but we should review it when we're done with toolbar update.
I will add a TODO in https://viamoinc.atlassian.net/browse/VMO-4192 to remind us.
Overview after fix:
> VMO-4330 add temporary solution to fix vertical scroll

- src/store/flow/flow.ts
This fixes Default showing up on multi-duplicate.
---
> VMO-4367 + VMO-4362 Fix when duplicating multiple blocks doesn't merge metadata

- src/components/interaction-designer/block-editors/BlockEditor.vue
- src/components/interaction-designer/block-types/ConsoleIO_PrintBlock.vue
- src/components/interaction-designer/block-types/ConsoleIO_ReadBlock.vue
- src/components/interaction-designer/block-types/Core_CaseBlock.vue
- src/components/interaction-designer/block-types/Core_LogBlock.vue
- src/components/interaction-designer/block-types/Core_OutputBlock.vue
- src/components/interaction-designer/block-types/Core_RunFlowBlock.vue
- src/components/interaction-designer/block-types/Core_SetContactPropertyBlock.vue
- src/components/interaction-designer/block-types/Core_SetGroupMembershipBlock.vue
- src/components/interaction-designer/block-types/MobilePrimitives_MessageBlock.vue
- src/components/interaction-designer/block-types/MobilePrimitives_NumericResponseBlock.vue
- src/components/interaction-designer/block-types/MobilePrimitives_OpenResponseBlock.vue
- src/components/interaction-designer/block-types/MobilePrimitives_SelectManyResponseBlock.vue
- src/components/interaction-designer/block-types/MobilePrimitives_SelectOneResponseBlock.vue
- src/components/interaction-designer/block-types/SmartDevices_LocationResponseBlock.vue
- src/components/interaction-designer/block-types/SmartDevices_PhotoResponseBlock.vue
- tests/unit/__snapshots__/storybook.spec.ts.snap
@safydy-r I used gif here instead of mov files as you suggested 👍  Thanks for sharing this, it is so much lighter!
> VMO-4210 Keep the block editor's header sticky to the top

- src/store/flow/block-types/MobilePrimitives_MessageBlockStore.ts
I don't know why we missed this condition to be `> 0` not `> 1` 😄
> VMO-4322 fix test condition

- src/components/interaction-designer/Block.vue
- src/components/interaction-designer/BuilderCanvas.vue
- src/components/interaction-designer/block/BlockToolbar.vue
- src/store/builder/index.ts
- src/views/InteractionDesigner.vue
**Note for devs:**
- To make sure the toolbar keeps the position `sticky` and behaves like `fixed`, I used this solution: https://stackoverflow.com/a/57452861/3256489
- I took the opportunity to silent some `NavigationDuplicated` errors like we do with validations https://github.com/FLOIP/flow-builder/blob/VMO-4403-fix-flow-builder-block-editor-position/src/components/interaction-designer/toolbar/ErrorNotifications.vue#L133
**Screenshot**
> Vmo 4403 fix toolbar position with scrolling

- src/store/flow/block-types/MobilePrimitives_NumericResponseBlockStore.ts
During some testing I noticed that the exit tests in the NumericResponseBlock were not valid expressions.
They are missing a parenthesis on the end.
This PR adds the missing paren.
> fix missing parens on numeric response block exits

- package.json
As per discussion on Slack, this is a small change to the package configuration, to use 
```
"engines": {
"node": "^14"
},
```
instead of, as before, `^14.19.1`.
> FEATURE-RELAX-NODE Use node version ^14 as engine constraint

- src/store/flow/block-types/BaseBlock.ts
- src/store/flow/block-types/SmartDevices_LocationResponseBlockStore.ts
- src/store/flow/block-types/SmartDevices_PhotoResponseBlockStore.ts
We used `initiateExtraVendorConfig` to add extra fields to block config. This PR follows the `vendor_metadata` idea and puts the returned attributes to `block.vendor_metadata` instead.
This PR targets https://github.com/FLOIP/flow-builder/pull/269 because we have app-wide changes there.
> VMO-6428 Move `initiateExtraVendorConfig` invocation

- src/components/interaction-designer/block-editors/choices/ChoiceMappingModal.vue
- src/components/interaction-designer/block-editors/choices/ChoicesBuilder.vue
- src/components/interaction-designer/block-editors/choices/TextMappingRow.vue
- src/components/interaction-designer/block-editors/choices/TextMappingTable.vue
- src/components/interaction-designer/block-editors/choices/TextSynonymsEditor.vue
- src/store/flow/block-types/MobilePrimitives_SelectOneResponseBlockStore.ts
- src/store/flow/block/choice.ts
Addressed checklists:
- Create `text_tests[]` for multiple languages when adding new choices
- Display synonyms for a specific language in a given tab
- Add and Edit synonyms for a specific language from within a tab
@object-required: I don't think we really need choices' vendor_metadata `voice_options` & `text_options`. See my remark at the miro doc (highlighted in red fonts) https://miro.com/app/board/uXjVOiur8ck=/?moveToWidget=3458764530346709331&cot=14
Overview
> VMO-6654 consider languages

- src/components/interaction-designer/block-editors/choices/ChoiceMappingModal.vue
- src/components/interaction-designer/block-editors/choices/ChoicesBuilder.vue
- src/components/interaction-designer/block-editors/choices/TextSynonymsEditor.vue
- src/components/interaction-designer/block-editors/choices/mixins/CommonVoiceChoiceConfig.vue
- src/components/interaction-designer/flow-editors/FlowEditor.vue
- src/components/interaction-designer/flow-editors/LanguagesEditor.vue
- src/store/flow/block.ts
- src/store/flow/block/choice.ts
Address changes:
- resolve all reactivity issues
- Fix the TAB active class when not having VOICE mode
- Fix TS errors
- Handle add/remove languages for active flow
- Display expressions, i.e., `@…` synonyms as is; while `@block.response` is displayed as plain text
> Feature/vmo 5463/vmo 6654/mcq text based mode mapping wip 10aug saf

- src/components/interaction-designer/Block.vue
- src/components/interaction-designer/Connection.vue
- src/components/interaction-designer/block-editors/BlockEditor.vue
- src/components/interaction-designer/blocks/BlockToolbar.vue
- src/store/builder/index.ts
- src/store/flow/block.ts
[Note for reviewers]
- the main change is to bring the block-toolbar inside the block-draggable, and try to reposition the connection start position because the exit might change
- another thing to consider: I've made a change about block colours, because I made a mistake by referring to a wrong dsn ([dns-261's iteration page](https://www.figma.com/file/nNnjLfJvgh44ZRpmxcb4jz/VMO-5668-%26-DSN-261%3A-Flow-Builder-in-Viamo-context?node-id=1%3A2)) instead of "[dsn-261's block states page](https://www.figma.com/file/nNnjLfJvgh44ZRpmxcb4jz/VMO-5668-%26-DSN-261%3A-Flow-Builder-in-Viamo-context)" which is linked with vmo-6573
@object-required / @bulatgab That dsn reference is very important !
[Overview]
> Feature/vmo 6714/update block activation state trigger

- src/components/interaction-designer/resource-editors/HorizontalResourceEditor.vue
- src/components/interaction-designer/resource-editors/LanguageResourceEditor.vue
- src/components/interaction-designer/resource-editors/ModeResourceEditor.vue
- src/components/interaction-designer/resource-editors/ResourceVariantTextEditor.vue
- src/components/interaction-designer/resource-editors/index.ts
- src/store/flow/flow.ts
TODO:
- will fix the validations on multiple languages (more than 3) in https://viamoinc.atlassian.net/browse/VMO-7102
Note for reviewer:
- For order, I used the `d-flex order` feature, that way we don't need to make hard refactor in the code base. Beside, the resource validation rely on a specific order.
[Overview]
Resource view
Block config: To see the order (IVR first)
> Feature/vmo 6851/vmo 7116/group resource UI by channel

- dist/types/store/resource-viewer/index.d.ts
- src/components/interaction-designer/block-editors/choices/ChoicesBuilder.vue
- src/store/flow/flow.ts
voto5 pr: https://bitbucket.org/voto/voto5/pull-requests/2890/vmo-7393-fix-resource-cleanup-when
1. When we are removing a choice, the resource is not orphan (the block is still there), so we should delete it directly, without checking for orphanhood
2. When we are removing a block, we should first remove the block, and then remove the orphan resources
Demo 1 - Delete block
Demo 2 - Delete choice
> Bugfix/vmo 7393/fix delete btn on blocks

- dist/types/components/interaction-designer/toolbar/TreeBuilderToolbar.vue.d.ts
- dist/types/views/InteractionDesigner.vue.d.ts
- src/components/interaction-designer/toolbar/TreeBuilderToolbar.vue
- src/views/InteractionDesigner.vue
Changes in this PR:
1. It adds a call to `setActiveMainComponent` in `created`
2. It moves the other `setActiveMainComponent` call from `updated` to a watcher, following the pattern for `modes`
The console error it is solving (when creating a new flow in voto5):
> Feature/vmo 7547/fix missing param component

- app.config.json
- builder.config.json
- vue-tsc.tsconfig.json
- remove `orgTimezone` to avoid confusion. Why we can do it:
- it doesn't contain correct value
- we are not using it in the community builder anyway
- add `skipLibCheck` to remove console errors from npm dependencies when running `vue-tsc`. Why:
- we don't control these libs and we can't fix them so there is no point in seeing the errors
> Feature/vmo 7383/minor fixes

- src/store/flow/block.ts
`block_addExit` inserts exits before the last element of `block.exits[]`, and we need it to append exits at the end instead. This PR introduces an optional parameter `append` to support this behaviour.
> CORE-67 Allow appending exits

- package.json
- src/components/interaction-designer/Block.vue
- src/store/builder/index.ts
- src/store/flow/block.ts
- src/views/InteractionDesigner.vue
[for reviewers]
There were 02 options:
- option1: make the `should_show_block_tool_bar` more configurable for the flow-builder consumer so we can hide this again if needed. 
- option2: deprecate `should_show_block_tool_bar` and remove related codes.
Option1 seems to be a good idea, but when I investigated the code, that conditional display affect the block height, and sometimes it introduce a complexity on the canvas. Eg: I remember dealing with it when we fixed the connection arrow. Therefore, I decided to choose option2.
[screen capture]
> Feature/core 246/always display block toolbar
